# Reading Student Scores with Pandas

My exploratory notebook.

## What is Jupyter Notebooks

Jupyter Notebooks is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations, and narrative text. It is widely used for data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning, and much more.

## Types of Cells

In Jupyter Notebooks, there are primarily two types of cells:

1. **Code Cells**: These cells allow you to write and execute code. You can run the code in these cells, and the output will be displayed directly below the cell. Code cells support various programming languages, but Python is the most commonly used language in Jupyter Notebooks.

2. **Markdown Cells**: These cells are used for writing text in Markdown format. You can use Markdown cells to add explanations, documentation, headings, lists, links, images, and other formatted text to your notebook. Markdown cells do not execute code; they are purely for text content.

## Markdown Syntax

Here are some common Markdown syntax elements you can use in Jupyter Notebooks:
- **Headings**: Use `#` for headings. More `#` symbols indicate smaller headings.
  - Example: `# Heading 1`, `## Heading 2`, `### Heading 3`
- **Bold Text**: Use `**` or `__` to make text bold.
  - Example: `**bold text**` or `__bold text__`
- **Italic Text**: Use `*` or `_` to italicize text.
  - Example: `*italic text*` or `_italic text_`
- **BOLD AND ITALIC**: Use `***` to use both bold and italic. ***Let's try it out***
- **Lists**: Use `-`, `*`, or `+` for unordered lists and numbers for ordered lists.
    - Example:
        - Unordered:
        - `- Item 1`
        - `- Item 2`
        - Ordered:
        1. `1. First item`
        2. `2. Second item`

## More on Markdown

- **Links**: Use `[text](URL)` to create hyperlinks.
  - Example: `[OpenAI](https://www.openai.com)`
- **Images**: Use `![alt text](image URL)` to embed images.
  - Example: `![Python Logo](https://www.python.org/static/community_logos/python-logo.png)`

## Markdown Documentation on Github

For more detailed information on Markdown syntax, you can refer to the official GitHub documentation: [Mastering Markdown](https://guides.github.com/features/mastering-markdown/).

## Mazs Paraugs

Neliela rindkopa kurā izceļam **šo tekstu** vai arī *slīprakstā*

### Noderīgas saites

* [RTU](https://www.rtu.lv/)
* [DAS](https://das.lv)
* [LSM](https://lsm.lv)

### Attēls

Bildēm vajag izsaukuma zīmi pirms saites

![RTU logo](https://www.rtu.lv/images/logo_lv.svg?v=1.1)

## Code cells

Unlike markdown/text cells, code cells are meant for Python or other language to interpet/execute run code.

Typically we have multiple cells.

Taken together, they are just like our normal .py Python code.

### Interactivity

Regular .py finishes and variables are lost

In Jupyter .ipynb variables/data live as long as notebook is active and cell has been run

In [1]:
print("Let's explore Jupyter Notebooks! :)")  # here we send a request to Python kernel and get response
print("Man patīk Python!")

Let's explore Jupyter Notebooks! :)
Man patīk Python!

In [5]:
print("Tagad pareiz izvads")

Tagad pareiz izvads

In [6]:
a = 10
b = 20
c = a + b
print("The sum of a and b is:", c)
# this is cell is over but our variables are still ALIVE!!!

The sum of a and b is: 30

In [11]:
# a, b, c are alive here if I run the cell above
print(a,b,c)

10 20 330

In [10]:
c += 100  # same as c = c + 100
print(f"c is now {c}")

c is now 330

## Golden Standard - Run ALL should work

When working, it might be useful to run some cells multiple times.

If I plan to share,preserve this work then Run All should work properly, that is each code cell is run once in order from top to bottom.

## Data Wrangling with Pandas

In [12]:
# Let's Show Datetime, Python and Pandas version
# import means we load the particular module / function for use in our code
import datetime # standard meaning comes with Python
import sys # again Python standard
import pandas as pd # Pandas is external , it is installed in by default
# note how I imported pandas as pd, this means we will use pd to address pandas specific functions instead of long pandas

print("Current datetime:", datetime.datetime.now())
print("Python version:", sys.version)
print("Pandas version:", pd.__version__)
# The script is over here well actually our notebook is still continuing
# we can write more code below!
# and we keep all the previous code above intact

Current datetime: 2026-01-22 17:13:15.778359
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Pandas version: 2.2.2

## More about Pandas

Pandas is the premiere data analysis library in Python.

So called "Excel on Steroids"..

### Official Page

[Pandas Page](https://pandas.pydata.org/)

## Loading Excel/CSV Files with Pandas

Pandas offers powerful tools for reading and manipulating data from Excel and CSV files. Here are some common functions used to load these files:
- **Reading CSV Files**: Use `pd.read_csv('file_path.csv')` to read a CSV file into a DataFrame.
- **Reading Excel Files**: Use `pd.read_excel('file_path.xlsx', sheet_name='Sheet1')` to read an Excel file into a DataFrame. You can specify the sheet name or index.

In [13]:
# import pandas as pd # we would uncomment this if we did not have pandas yet
# let's start with reading a csv file using pandas
# data_csv = pd.read_csv('grades_jan.csv') # this would load from current folder
# instead we will read from the code repository that is our web address
data_csv = pd.read_csv("https://raw.githubusercontent.com/ValRCS/RTU_Automating_Tasks_With_Python/refs/heads/main/src/topic_4_excel_csv_pandas_sets/grades_jan.csv")
# read_csv has many extra options
# full documentation is here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
# show the first 5 rows of the dataframe
# shape of the dataframe
print(f"CSV data has {data_csv.shape[0]} rows and {data_csv.shape[1]} columns.")
print(f"Shape of the CSV data: {data_csv.shape}")
print("First 5 rows of the CSV data:")
data_csv.head() # default is 5 rows but we can add a number inside head() function

CSV data has 30 rows and 5 columns.
Shape of the CSV data: (30, 5)
First 5 rows of the CSV data:

   student_id student_name   course  grade month
0           1        Alice     Math     83   Jan
1           1        Alice  Physics     76   Jan
2           1        Alice  Biology     85   Jan
3           2          Bob     Math     73   Jan
4           2          Bob  Physics     77   Jan

In [14]:
# let's save the dateframe locally into csv with name student_data_jan.csv
data_csv.to_csv('student_data_jan.csv', index=False) # index=False means we do not want to save the row indices

In [15]:
# we can be lazy with notebook
# we do not have to use print for last row in the cell
5 + 4 # so last row output is shown

9

In [16]:
# let's get some info on the dataframe
print("Information about the CSV data:")
data_csv.info() # again we utilize the fact that last row is automatically shown

Information about the CSV data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    30 non-null     int64
 1   student_name  30 non-null     object
 2   course        30 non-null     object
 3   grade         30 non-null     int64
 4   month         30 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.3+ KB

In [17]:
# let's read an excel file called students.xlsx
students = pd.read_excel('https://raw.githubusercontent.com/ValRCS/RTU_Automating_Tasks_With_Python/refs/heads/main/src/topic_4_excel_csv_pandas_sets/students.xlsx')
# if you need to specify you can show the sheet name or index
# students = pd.read_excel('students.xlsx', sheet_name='Sheet1')
# shape
print(f"Excel data has {students.shape[0]} rows and {students.shape[1]} columns.")
# head
print("First 7 students from the Excel data:")
students.head(7)

Excel data has 10 rows and 4 columns.
First 7 students from the Excel data:

   student_id first_name last_name                       email
0           1      Alice     Smith     alice.smith@example.com
1           2        Bob   Johnson     bob.johnson@example.com
2           3      Carol  Williams  carol.williams@example.com
3           4       Dave     Brown      dave.brown@example.com
4           5        Eve     Jones       eve.jones@example.com
5           6      Frank    Miller    frank.miller@example.com
6           7      Grace     Davis     grace.davis@example.com

In [18]:
# let's get last 4 students from the Excel data
print("Last 4 students from the Excel data:")
students.tail(4) # default for tail is also 5 just like head

Last 4 students from the Excel data:

   student_id first_name last_name                      email
6           7      Grace     Davis    grace.davis@example.com
7           8      Heidi    Wilson   heidi.wilson@example.com
8           9       Ivan    Taylor    ivan.taylor@example.com
9          10       Judy  Anderson  judy.anderson@example.com

In [21]:
# we can also get a random sample of rows
# this can be very handy when working with large datasets
print("Random sample of 5 students from the Excel data:")
students.sample(5)

Random sample of 5 students from the Excel data:

   student_id first_name last_name                     email
7           8      Heidi    Wilson  heidi.wilson@example.com
0           1      Alice     Smith   alice.smith@example.com
5           6      Frank    Miller  frank.miller@example.com
3           4       Dave     Brown    dave.brown@example.com
8           9       Ivan    Taylor   ivan.taylor@example.com

In [25]:
# if I want a specific sample I supply seed
students.sample(5, random_state=2026) # so everyone will get same sample, it is pseudo-random

   student_id first_name last_name                      email
7           8      Heidi    Wilson   heidi.wilson@example.com
3           4       Dave     Brown     dave.brown@example.com
9          10       Judy  Anderson  judy.anderson@example.com
8           9       Ivan    Taylor    ivan.taylor@example.com
4           5        Eve     Jones      eve.jones@example.com

In [26]:
# you can also get rows by numeric index using iloc
print("Students from index 3 to 7:")
students.iloc[3:8] # so number 8 is not shown

Students from index 3 to 7:

   student_id first_name last_name                     email
3           4       Dave     Brown    dave.brown@example.com
4           5        Eve     Jones     eve.jones@example.com
5           6      Frank    Miller  frank.miller@example.com
6           7      Grace     Davis   grace.davis@example.com
7           8      Heidi    Wilson  heidi.wilson@example.com

In [27]:
# Pandas also offers regular indexing using loc
# for example, if the dataframe has a column named 'first_name', you can do:
students.loc[students['first_name'] == 'Dave']

   student_id first_name last_name                   email
3           4       Dave     Brown  dave.brown@example.com

In [28]:
# we can also get all students with student_id over 5
students.loc[students['student_id'] > 5]

   student_id first_name last_name                      email
5           6      Frank    Miller   frank.miller@example.com
6           7      Grace     Davis    grace.davis@example.com
7           8      Heidi    Wilson   heidi.wilson@example.com
8           9       Ivan    Taylor    ivan.taylor@example.com
9          10       Judy  Anderson  judy.anderson@example.com

In [29]:
# we can get all rows from data_csv which have grade above 90
data_csv.loc[data_csv['grade'] > 90]

    student_id student_name   course  grade month
10           4         Dave  Physics     98   Jan
20           7        Grace  Biology     92   Jan
21           8        Heidi     Math     96   Jan
24           9         Ivan     Math     91   Jan

In [30]:
# if I wanted to save a fresh copy of some filtered results to a new variable
filtered_students = students.loc[students['student_id'] > 5] # creates a new dataframe
# actually it is not a full copy but a view of the original dataframe
# so any changes to filtered_students will also affect students dataframe unless we make a full copy
# actual full copy of filtered results
filtered_students_copy = filtered_students.copy()
# show both dataframes
display(filtered_students.head())  #note instead of print we use display to show dataframe in middle of cell
# copy
display(filtered_students_copy.head())

   student_id first_name last_name                      email
5           6      Frank    Miller   frank.miller@example.com
6           7      Grace     Davis    grace.davis@example.com
7           8      Heidi    Wilson   heidi.wilson@example.com
8           9       Ivan    Taylor    ivan.taylor@example.com
9          10       Judy  Anderson  judy.anderson@example.com

   student_id first_name last_name                      email
5           6      Frank    Miller   frank.miller@example.com
6           7      Grace     Davis    grace.davis@example.com
7           8      Heidi    Wilson   heidi.wilson@example.com
8           9       Ivan    Taylor    ivan.taylor@example.com
9          10       Judy  Anderson  judy.anderson@example.com

In [31]:
# we can use describe to show some statistics about numeric columns
print("Statistical summary of the grade data:")
data_csv.describe()

Statistical summary of the grade data:

       student_id     grade
count   30.000000  30.00000
mean     5.500000  76.50000
std      2.921384  11.19344
min      1.000000  60.00000
25%      3.000000  67.00000
50%      5.500000  77.00000
75%      8.000000  85.00000
max     10.000000  98.00000

In [32]:
# you can also describe non-numeric columns by specifying include='all'
#print("Statistical summary of all columns in the grade data:")
data_csv.describe(include='all')

        student_id student_name course     grade month
count    30.000000           30     30  30.00000    30
unique         NaN           10      3       NaN     1
top            NaN        Alice   Math       NaN   Jan
freq           NaN            3     10       NaN    30
mean      5.500000          NaN    NaN  76.50000   NaN
std       2.921384          NaN    NaN  11.19344   NaN
min       1.000000          NaN    NaN  60.00000   NaN
25%       3.000000          NaN    NaN  67.00000   NaN
50%       5.500000          NaN    NaN  77.00000   NaN
75%       8.000000          NaN    NaN  85.00000   NaN
max      10.000000          NaN    NaN  98.00000   NaN

In [33]:
# we can show columns alone as a list
print("Columns in the CSV data:")
column_list = data_csv.columns.tolist()
print(column_list)

Columns in the CSV data:
['student_id', 'student_name', 'course', 'grade', 'month']

In [34]:
# so let's see head of first 8 of only student_name and course and grade columns
data_csv[['student_name', 'course', 'grade']].head(8)
# note the double square brackets [[]] when selecting multiple columns
# essentially we are passing a list of column names to the dataframe

  student_name   course  grade
0        Alice     Math     83
1        Alice  Physics     76
2        Alice  Biology     85
3          Bob     Math     73
4          Bob  Physics     77
5          Bob  Biology     85
6        Carol     Math     61
7        Carol  Physics     78

## Using SQL like syntax in PANDAS

We can use syntax similar to SQL to filter our results

In [35]:
# Pandas offers many different approaches for filtering, working with data
# We can use SQL like syntax for our data queries

data_csv.query('grade > 90')
# more on query docs at Pandas: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html#pandas.DataFrame.query

    student_id student_name   course  grade month
10           4         Dave  Physics     98   Jan
20           7        Grace  Biology     92   Jan
21           8        Heidi     Math     96   Jan
24           9         Ivan     Math     91   Jan

In [36]:
# compare above SQL approach with other syntax or filtering
data_csv[data_csv['grade'] > 90]

    student_id student_name   course  grade month
10           4         Dave  Physics     98   Jan
20           7        Grace  Biology     92   Jan
21           8        Heidi     Math     96   Jan
24           9         Ivan     Math     91   Jan

In [37]:
# we could get a single column as well
data_csv['student_name'].head(4)
# here the output was actually a Pandas Series not a DataFrame
# Series is like a single column dataframe with some extra features
# or you can think of Dataframe as a collection of Series objects

0    Alice
1    Alice
2    Alice
3      Bob
Name: student_name, dtype: object

In [38]:
# let's create a new column for students
# they all go to RTU
students['university'] = 'RTU' # so we copied the string 'RTU' to all rows in the new column
# let's take a sample
students.sample(5)

   student_id first_name last_name                     email university
3           4       Dave     Brown    dave.brown@example.com        RTU
0           1      Alice     Smith   alice.smith@example.com        RTU
6           7      Grace     Davis   grace.davis@example.com        RTU
8           9       Ivan    Taylor   ivan.taylor@example.com        RTU
5           6      Frank    Miller  frank.miller@example.com        RTU

In [39]:
# we can rename last_name column to surname
students.rename(columns={'last_name': 'surname'}, inplace=True)
# inplace means that we modify the original dataframe directly
students.head()

   student_id first_name   surname                       email university
0           1      Alice     Smith     alice.smith@example.com        RTU
1           2        Bob   Johnson     bob.johnson@example.com        RTU
2           3      Carol  Williams  carol.williams@example.com        RTU
3           4       Dave     Brown      dave.brown@example.com        RTU
4           5        Eve     Jones       eve.jones@example.com        RTU

In [40]:
students.rename(columns={'first_name': 'name'}, inplace=True) # inplace means that students dataframe is being modified without new variable creation
students.head()

   student_id   name   surname                       email university
0           1  Alice     Smith     alice.smith@example.com        RTU
1           2    Bob   Johnson     bob.johnson@example.com        RTU
2           3  Carol  Williams  carol.williams@example.com        RTU
3           4   Dave     Brown      dave.brown@example.com        RTU
4           5    Eve     Jones       eve.jones@example.com        RTU

In [41]:
# so let's load february grades as well
feb_url = "https://raw.githubusercontent.com/ValRCS/RTU_Automating_Tasks_With_Python/refs/heads/main/src/topic_4_excel_csv_pandas_sets/grades_feb.csv"
feb_grades = pd.read_csv(feb_url)
# show first 5 rows
feb_grades.head()

   student_id student_name   course  grade month
0           1        Alice     Math     64   Feb
1           1        Alice  Physics     70   Feb
2           1        Alice  Biology     80   Feb
3           2          Bob     Math     72   Feb
4           2          Bob  Physics     88   Feb

In [43]:
# print columns for both january and february
print("Columns in the January data:")
print(data_csv.columns.tolist())
print("Columns in the February data:")
print(feb_grades.columns.tolist())
# are they equal?
print(f"Are the columns equal? {data_csv.columns.tolist() == feb_grades.columns.tolist()}")

Columns in the January data:
['student_id', 'student_name', 'course', 'grade', 'month']
Columns in the February data:
['student_id', 'student_name', 'course', 'grade', 'month']
Are the columns equal? True

In [44]:
# so now let's combine our january and february grades into a single dataframe
# in order for this concat to work
# we need the same columns in both dataframes
all_grades = pd.concat([data_csv, feb_grades], ignore_index=True)
# shape of all_grades
print(f"All grades data has {all_grades.shape[0]} rows and {all_grades.shape[1]} columns.")

All grades data has 60 rows and 5 columns.

In [46]:
# let's sort the grades by student_name
all_grades_sorted = all_grades.sort_values(by='student_name') # here I did not use inplace paramater because I wanted to keep the original order
all_grades_sorted.head(10)

    student_id student_name   course  grade month
0            1        Alice     Math     83   Jan
32           1        Alice  Biology     80   Feb
31           1        Alice  Physics     70   Feb
30           1        Alice     Math     64   Feb
2            1        Alice  Biology     85   Jan
1            1        Alice  Physics     76   Jan
4            2          Bob  Physics     77   Jan
3            2          Bob     Math     73   Jan
35           2          Bob  Biology     63   Feb
34           2          Bob  Physics     88   Feb

In [47]:
# we can sort by more than one column as well
# let's sort by name and course
all_grades_sorted_multi = all_grades.sort_values(by=['student_name', 'course'])
# there is also a way to sort in descending order
# so course will be tie breaker when there are multiple entries for the same student_name
all_grades_sorted_multi.head(10)

    student_id student_name   course  grade month
2            1        Alice  Biology     85   Jan
32           1        Alice  Biology     80   Feb
0            1        Alice     Math     83   Jan
30           1        Alice     Math     64   Feb
1            1        Alice  Physics     76   Jan
31           1        Alice  Physics     70   Feb
5            2          Bob  Biology     85   Jan
35           2          Bob  Biology     63   Feb
3            2          Bob     Math     73   Jan
33           2          Bob     Math     72   Feb

In [48]:
# i can sort by 3 columns just add grade as 3rd column to sort by
all_grades_sorted_multi = all_grades.sort_values(by=['student_name', 'course', 'grade'])
all_grades_sorted_multi.head(10)

    student_id student_name   course  grade month
32           1        Alice  Biology     80   Feb
2            1        Alice  Biology     85   Jan
30           1        Alice     Math     64   Feb
0            1        Alice     Math     83   Jan
31           1        Alice  Physics     70   Feb
1            1        Alice  Physics     76   Jan
35           2          Bob  Biology     63   Feb
5            2          Bob  Biology     85   Jan
33           2          Bob     Math     72   Feb
3            2          Bob     Math     73   Jan

In [49]:
# Oops we meant to sort by student_name and course in ascending order but by month in descending order
all_grades_sorted_multi = all_grades.sort_values(by=['student_name', 'course', 'month'], ascending=[True, True, False]) # so by list column values are matches to ascending Boolean Flag values so student_name is Ascending, course is Ascending and month is Descending
all_grades_sorted_multi.head(10)

    student_id student_name   course  grade month
2            1        Alice  Biology     85   Jan
32           1        Alice  Biology     80   Feb
0            1        Alice     Math     83   Jan
30           1        Alice     Math     64   Feb
1            1        Alice  Physics     76   Jan
31           1        Alice  Physics     70   Feb
5            2          Bob  Biology     85   Jan
35           2          Bob  Biology     63   Feb
3            2          Bob     Math     73   Jan
33           2          Bob     Math     72   Feb

In [50]:
# let's save our combined grades to a new csv file
all_grades_sorted_multi.to_csv('all_grades_sorted_multi.csv', index=False) # index=False means we do not want to save the row indices

In [51]:
# we can also save to excel
all_grades_sorted_multi.to_excel('all_grades_sorted_multi.xlsx', index=False)

## Downloading Data from Google Colab

If you are using Google Colab then Google offers an easy library to automatically download files

In [52]:
# let's download the all_grades files
from google.colab import files # Special library from Google
# if we are downloading multiple files at once we might need to aprove once from Chrome
files.download('all_grades_sorted_multi.csv')
files.download('all_grades_sorted_multi.xlsx')

## Mounting and loading and saving from Google Drive

In [53]:
# let's mount google drive
from google.colab import drive
drive.mount('/content/drive')
#

Mounted at /content/drive

In [54]:
# let's save the all grades into /content/drive/MyDrive/StudentuDati
all_grades_sorted_multi.to_csv('/content/drive/MyDrive/StudentuDati/all_grades_sorted_multi.csv', index=False)
# same goes for excel
all_grades_sorted_multi.to_excel('/content/drive/MyDrive/StudentuDati/all_grades_sorted_multi.xlsx', index=False)
#

In [55]:
# let's load the saved excel into grades_df  variable
grades_df = pd.read_excel('/content/drive/MyDrive/StudentuDati/all_grades_sorted_multi.xlsx')
# show first 5 rows
grades_df.head()

   student_id student_name   course  grade month
0           1        Alice  Biology     85   Jan
1           1        Alice  Biology     80   Feb
2           1        Alice     Math     83   Jan
3           1        Alice     Math     64   Feb
4           1        Alice  Physics     76   Jan

## Aggregation Analysis with Group By

We can perform analysis by grouping by one column and then aggregrating by another column

In [56]:
# first let's show value counts for student_name column
# that is how many values are for each unique entry in this column
all_grades.value_counts('student_name')

student_name
Alice    6
Bob      6
Carol    6
Dave     6
Eve      6
Frank    6
Grace    6
Heidi    6
Ivan     6
Judy     6
Name: count, dtype: int64

In [59]:
# let's group by student_name and get average grade
student_avg_grade = all_grades.groupby('student_name')['grade'].mean().round(2)
student_avg_grade.head(10) # we know here we only have 10 students :0
#

student_name
Alice    76.33
Bob      76.33
Carol    76.00
Dave     84.50
Eve      72.67
Frank    75.33
Grace    84.83
Heidi    82.00
Ivan     79.50
Judy     74.17
Name: grade, dtype: float64

In [61]:
# we can group by more than one column
# so let's group by student_name and then course and again find mean
student_course_avg_grade = all_grades.groupby(['student_name', 'course'])['grade'].mean().round(2)
# let's show full table
student_course_avg_grade
#

student_name  course
Alice         Biology    82.5
              Math       73.5
              Physics    73.0
Bob           Biology    74.0
              Math       72.5
              Physics    82.5
Carol         Biology    76.5
              Math       67.5
              Physics    84.0
Dave          Biology    79.5
              Math       75.5
              Physics    98.5
Eve           Biology    65.0
              Math       75.5
              Physics    77.5
Frank         Biology    73.5
              Math       82.0
              Physics    70.5
Grace         Biology    92.5
              Math       80.0
              Physics    82.0
Heidi         Biology    74.5
              Math       90.0
              Physics    81.5
Ivan          Biology    79.0
              Math       76.0
              Physics    83.5
Judy          Biology    69.0
              Math       85.0
              Physics    68.5
Name: grade, dtype: float64

In [62]:
# since this analysis is also a dataframe we can save it as well
student_course_avg_grade.to_csv('student_course_avg_grade.csv')

In [63]:
# I can then download it to localy computer
files.download('student_course_avg_grade.csv')
#

In [ ]:
# i could have also saved in my Google Drive assuming it was mounted